package ui;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.Test;
import playwright.PlaywrightActions;
import core.ui.UiActions;

import java.nio.file.Path;

import static org.junit.Assert.*;

public class PlaywrightActionsTest {
    private UiActions ui;
    private HtmlTestPage.Pages pages;

    @Before
    public void setUp() {
        pages = HtmlTestPage.create();
        // Headless true for CI stability
        ui = new PlaywrightActions(true);
    }

    @After
    public void tearDown() {
        if (ui != null) {
            ui.close();
        }
    }

    @AfterClass
    public static void printCoverageLocation() {
        // In CI/test runner without Maven, we still print where reports would be generated by Maven JaCoCo
        System.out.println("JaCoCo coverage report: target/site/jacoco/index.html");
        System.out.println("JaCoCo exec data: target/jacoco.exec");
    }

    @Test
    public void testBasicInteractions() {
        ui.open(pages.page1.toUri().toString());

        assertEquals("Test Page", ui.title());
        assertTrue(ui.url().startsWith("file:"));

        // exists and visibility
        assertTrue(ui.exists("#text"));
        assertTrue(ui.isVisible("#text"));

        // getText
        assertEquals("Hello World", ui.getText("#text").trim());

        // attribute
        assertEquals("greeting", ui.attribute("#text", "data-custom"));

        // value + compose
        assertEquals("", ui.value("#name"));
        ui.compose("#name", "Alice");
        assertEquals("Alice", ui.value("#name"));
        // value() fallback path on non-input element should return text content
        assertEquals("Hello World", ui.value("#text").trim());

        // focus should set attribute via onfocus script
        ui.focus("#name");
        assertEquals("true", ui.attribute("#name", "data-focused"));

        // click and verify result text
        ui.click("#btn");
        assertEquals("Clicked!", ui.getText("#clickResult"));

        // hover reveals sibling
        ui.hover("#hoverTarget");
        assertTrue(ui.isVisible("#hoverResult"));

        // delayed visibility
        ui.waitForVisible("#delayed", 3000);
        assertTrue(ui.isVisible("#delayed"));

        // screenshot
        Path shot = Path.of(System.getProperty("java.io.tmpdir"), "pw-shot.png");
        ui.screenshot(shot.toString());
        assertTrue(java.nio.file.Files.exists(shot));

        // navigation and back
        ui.click("#nav");
        assertEquals("Second Page", ui.title());
        ui.back();
        assertEquals("Test Page", ui.title());
    }
}
